export const listTeam = [
  {
    id: 1,
    name: "Felipe Morales",
    office: "Desenvolvedor Backend - Gestor de Projetos",
    instagram: "https://www.instagram.com/fe.moraless/",
    github: "https://github.com/FelipeMoralesdev",
    linkedin: "https://www.linkedin.com/in/felipemoraless/",
    image: "/images/team/felipe.jpeg",
  },
  {
    id: 2,
    name: "Gabriela Godoi",
    office: "Desenvolvedora Full Stack",
    instagram: "https://www.instagram.com/igwabriela",
    github: "https://github.com/gabrielagodoi",
    linkedin: "https://www.linkedin.com/in/gabriela-godoi-a434bb18a",
    image: "/images/team/gabriela.jpeg",
  },
  {
    id: 3,
    name: "Luana Belmiro",
    office: "Desenvolvedora Full Stack - Design UI UX",
    instagram: null,
    github: "https://github.com/LUANABELMIRO",
    linkedin: "https://www.linkedin.com/in/luana-belmiro-8a3300239/",
    image: "/images/team/luana.jpeg",
  },
  {
    id: 4,
    name: "Marcelle De Oliveira",
    office: "Desenvolvedora Frontend",
    instagram: null,
    github: "https://github.com/Marcelle-1",
    linkedin: "https://www.linkedin.com/in/marcelle-oliveira/",
    image: "/images/team/marcelle.jpeg",
  },
  {
    id: 5,
    name: "Nicolas Braga",
    office: "Desenvolvedor Full Stack",
    instagram: "https://www.instagram.com/nclsbraga_dev",
    github: "https://github.com/nbraga",
    linkedin: "https://www.linkedin.com/in/nbraga2022",
    image: "/images/team/nicolas.jpg",
  },
  {
    id: 6,
    name: "Poliana Yukie",
    office: "Desenvolvedora Full Stack",
    instagram: "https://www.instagram.com/polianayukietasaka/",
    github: "https://github.com/PolianaYukie",
    linkedin: "https://www.linkedin.com/in/poliana-yukie-tasaka-275376b0",
    image: "/images/team/poliana.jpeg",
  },
];
