export const listParticipants = [
  {
    id: 1,
    name: "Alessandra Marques",
    office: "Psicóloga e Graduanda em Pedagogia",
    image: "/images/participants/alessandra.jpg",
  },
  {
    id: 2,
    name: "Tatiane Fernandes",
    office: "Engenheira de Produção Cultural",
    image: "/images/participants/tatiane.jpeg",
  },
  {
    id: 3,
    name: "Eric Max",
    office: "Artivista, Ator e Produtor Cultural",
    image: "/images/participants/eric.jpeg",
  },
  {
    id: 4,
    name: "Gabriela Amorim",
    office: "Data Analyst",
    image: "/images/participants/gabriela.jpeg",
  },
  {
    id: 5,
    name: "Mariana Almeida",
    office: "Professora de Engenharia Econômica",
    image: "/images/participants/mariana-almeida.jpg",
  },
  {
    id: 6,
    name: "Mariana Zancanaro",
    office: "Brand Strategist",
    image: "/images/participants/mariana-zancanaro.jpeg",
  },
  {
    id: 7,
    name: "Luiza Ribeiro",
    office: "Psicóloga",
    image: "/images/participants/luiza.jpeg",
  },
  {
    id: 8,
    name: "Diego Guedes",
    office: "Account Mananger",
    image: "/images/participants/diego.jpeg",
  },
  {
    id: 9,
    name: "Renan Francisco",
    office: "Programador Full Stack",
    image: "/images/participants/renan.jpeg",
  },
  {
    id: 10,
    name: "Andréia Rodrigues",
    office: "Pós-graduada em Arte Educação",
    image: "/images/participants/andreia.jpeg",
  },
  {
    id: 11,
    name: "Juliana de Paula",
    office: "Professora Educação Infantil",
    image: "/images/participants/juliana.jpeg",
  },
  {
    id: 12,
    name: "Thais Novaes",
    office: "Professora Ensino Fundamental",
    image: "/images/participants/thais.jpeg",
  },
  {
    id: 13,
    name: "Cássia Ferreira",
    office: "Educadora Educação Infantil",
    image: "/images/participants/cassia.jpeg",
  },
  {
    id: 14,
    name: "Bianca Figueredo",
    office: "Educadora Educação Popular",
    image: "/images/participants/bianca.jpeg",
  },
  {
    id: 15,
    name: "Maria Carolina",
    office: "Produtora Multimída",
    image: "/images/participants/maria-carolina.jpeg",
  },
  {
    id: 16,
    name: "Maria Clara",
    office: "Cientista Social e Fotógrafa",
    image: "/images/participants/maria-clara.jpeg",
  },
  {
    id: 17,
    name: "Lucas Lima",
    office: "Biológo",
    image: "/images/participants/lucas.jpeg",
  },
  {
    id: 18,
    name: "Filipe Davi",
    office: "Desenvolvedor Web",
    image: "/images/participants/filipe.jpeg",
  },
  {
    id: 19,
    name: "Beethoven Lima",
    office: "Analista de Projetos e Analista de Sistemas",
    image: "/images/participants/beethoven.jpg",
  },
  {
    id: 20,
    name: "Gustavo Melo",
    office: "Artista",
    image: "/images/participants/gustavo.jpeg",
  },
];
